x = int(input('Num 1 : '))
y = int(input('Num 2 : '))
c = []
c.append(x)
c.append(y)
print('ADD : ', c[0] + c[1])
print('SUB : ', c[0] - c[1])
print('MUL : ', c[0] * c[1])
print('DIV : ', c[0] / c[1])
print('Double DIV : ', c[0] // c[1])
print('Square : ', c[0] ** c[1])
print('MOD : ', c[0] % c[1])
